import { ArrowUpRight, BookOpen, CheckCircle2, Code2, Cpu, Gauge, Layers3, ShieldCheck } from "lucide-react";
import SectionLabel from "./SectionLabel";

type Note = { icon: typeof ShieldCheck; label: string; title: string; body?: string; story?: { label: string; text: string }[] };

const notes: Note[] = [
  { icon: ShieldCheck, label: "evaluation", title: "A simple model can be the right model", story: [{ label: "the signal", text: "TF-IDF + Logistic Regression reached 98.69% test accuracy on the ISOT dataset." }, { label: "the lesson", text: "A clean evaluation boundary and resolved feature-selection leakage risk mattered more than adding unnecessary model complexity." }] },
  { icon: Cpu, label: "ai systems", title: "AI should create leverage, not hide the engineering", body: "Useful AI products connect model output to clear states, structured responses, fallbacks, and visible evidence. The model is one part of the product—not the product itself." },
  { icon: Gauge, label: "optimization", title: "Constraints make systems clearer", story: [{ label: "the problem", text: "Scheduling becomes difficult when rooms, teachers, batches, availability, lab blocks, and repeat courses interact." }, { label: "the approach", text: "SmartSched uses a Genetic Algorithm, validation, edge-case testing, and a bounded runtime budget to keep results practical." }] },
  { icon: ShieldCheck, label: "privacy", title: "The safest data flow is often the shortest one", body: "ResumeLens keeps PDF parsing in the browser with pdf.js and keeps the API key server-side. Privacy is stronger when sensitive data takes fewer unnecessary trips." },
  { icon: BookOpen, label: "delivery", title: "A working feature is not a shipped feature", story: [{ label: "the gap", text: "A local ResumeLens flow was only the beginning; reliable delivery needed a repeatable path after code changed." }, { label: "the system", text: "Docker, GitHub Actions, GHCR, and Railway made the backend and deployment process easier to verify end to end." }] },
  { icon: Gauge, label: "computer vision", title: "Performance is a design decision", body: "The AR gesture experiment uses cached sprites and downscaled detection frames to preserve responsiveness on integrated graphics instead of assuming dedicated hardware." },
  { icon: Code2, label: "re-engineering", title: "Refactoring is product work", story: [{ label: "the responsibility", text: "The Food Ordering System was improved by taking over an existing codebase rather than discarding it." }, { label: "the outcome", text: "Modern C++, modular OOP, dependency injection, memory-leak fixes, and safer input handling made the system easier to evolve." }] },
  { icon: Layers3, label: "architecture", title: "Separate the interface from the intelligence", body: "Across legal research, résumé analysis, and commerce work, the most maintainable shape is a clear boundary between user experience, API orchestration, model services, and data access." },
  { icon: Cpu, label: "product thinking", title: "A feature earns trust through context", story: [{ label: "the observation", text: "Users need to understand why an AI result is useful, especially when the result affects a legal search, résumé decision, or purchase." }, { label: "the design", text: "Citation visibility, section-level feedback, confidence-aware language, and clear next actions make the output easier to inspect and use." }] },
];

export default function TechnicalNotes() {
  return <section id="notes" className="technical-notes px-6 py-24"><div className="mx-auto max-w-5xl"><SectionLabel index="07" label="technical notes" /><div className="technical-notes__intro"><div><p className="technical-notes__eyebrow">/ engineering perspective</p><h2>How I think about <span>the build.</span></h2></div><p>Short notes from the decisions, constraints, and trade-offs behind the work.</p></div><div className="technical-notes__grid">{notes.map(({ icon: Icon, label, title, body, story }) => <article className="technical-note" key={title}><div className="technical-note__top"><span><Icon size={15} /> {label}</span><ArrowUpRight size={14} /></div><h3>{title}</h3>{body ? <p className="technical-note__body">{body}</p> : <div className="technical-note__story">{story?.map((item) => <p key={item.label}><strong>{item.label}</strong>{item.text}</p>)}</div>}<span className="technical-note__read"><CheckCircle2 size={11} /> documented build lesson</span></article>)}</div></div></section>;
}
