import { ArrowUpRight, BookOpen, CheckCircle2, Cpu, Gauge, ShieldCheck } from "lucide-react";
import SectionLabel from "./SectionLabel";

const notes = [
  { icon: ShieldCheck, label: "evaluation", title: "A simple model can be the right model", expected: "I expected a heavier model to be necessary for useful classification.", result: "The simpler TF-IDF + Logistic Regression approach reached 98.69% test accuracy on the ISOT dataset.", decision: "I used a clean evaluation boundary and resolved a feature-selection leakage risk so the result stayed meaningful." },
  { icon: Cpu, label: "ai systems", title: "AI should create leverage, not hide the engineering", expected: "I expected model output alone would not be enough to make an AI feature useful.", result: "The strongest flows became the ones that connected model output to clear states, structured responses, and visible evidence.", decision: "I used prompt design, server-side model calls, fallbacks, and user-facing context to turn intelligence into a dependable workflow." },
  { icon: Gauge, label: "optimization", title: "Constraints make systems clearer", expected: "I expected academic scheduling to become difficult once rooms, teachers, batches, and availability interacted.", result: "SmartSched’s design made the constraints explicit instead of hiding them inside an opaque result.", decision: "I used a Genetic Algorithm with validation, edge-case testing, and a bounded runtime budget to keep the output practical." },
  { icon: ShieldCheck, label: "privacy", title: "The safest data flow is often the shortest one", expected: "I expected résumé analysis to need a file-upload pipeline before feedback could begin.", result: "Keeping parsing in the browser meant raw résumé data was not persisted by default before analysis.", decision: "I used client-side pdf.js parsing and kept the API key server-side so privacy and security were part of the architecture." },
  { icon: BookOpen, label: "delivery", title: "A working feature is not the same as a shipped feature", expected: "I expected the first working ResumeLens flow to be enough to call the product finished.", result: "The project became more reliable after the backend was modularized, containerized, and verified through CI/CD.", decision: "I used Docker, GitHub Actions, GHCR, and Railway deployment to make the path from change to deployed behavior repeatable." },
  { icon: Gauge, label: "computer vision", title: "Performance is a design decision", expected: "I expected real-time hand tracking to struggle on everyday integrated graphics.", result: "The AR experiment stayed responsive by reducing the work done on each frame.", decision: "I used cached sprites and downscaled detection frames to solve the hardware constraint without requiring a dedicated GPU." },
];

export default function TechnicalNotes() {
  return <section id="notes" className="technical-notes px-6 py-24"><div className="mx-auto max-w-5xl"><SectionLabel index="07" label="technical notes" /><div className="technical-notes__intro"><div><p className="technical-notes__eyebrow">/ engineering perspective</p><h2>How I think about <span>the build.</span></h2></div><p>Short notes from the decisions, constraints, and trade-offs behind the work.</p></div><div className="technical-notes__grid">{notes.map(({ icon: Icon, label, title, expected, result, decision }) => <article className="technical-note" key={title}><div className="technical-note__top"><span><Icon size={15} /> {label}</span><ArrowUpRight size={14} /></div><h3>{title}</h3><div className="technical-note__story"><p><strong>Expected</strong>{expected}</p><p><strong>What happened</strong>{result}</p><p><strong>What I used</strong>{decision}</p></div><span className="technical-note__read"><CheckCircle2 size={11} /> documented build lesson</span></article>)}</div></div></section>;
}
